set BUILD_PLATFORM=win32-64
set BUILD_DIR=build-%BUILD_PLATFORM%
set BUILD_TYPE=Release
set BUILD_SHARED_LIBS=OFF
set BUILD_STATIC_LIBS=ON
REM set INSTALL_DIR=install-%BUILD_PLATFORM%

IF EXIST %BUILD_DIR% rmdir %BUILD_DIR% /s /q
mkdir %BUILD_DIR%
cd %BUILD_DIR%

cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=%INSTALL_DIR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -DMINIMIZE_SIZE=ON -DBUILD_WITH_STATIC_CRT=OFF

cmake --build . --config %BUILD_TYPE%